version: '3.9'

services:
  db:
    image: postgres:15.4
    environment:
      - POSTGRES_DB=se_docker
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  backend:
    build:
      context: "."
      dockerfile: Dockerfile.backend
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - db
  
  web:
    image: nginx:1.25.2
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    depends_on:
      - backend