version: '3.2'

services:
  db:
    image: postgres:15.4
    environment:
      - POSTGRES_DB=se_docker
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  backend:
    build:
      context: "."
      dockerfile: Dockerfile.backend
    ports:
      - 80:80
    depends_on:
      - db